name: Linting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  flake8_lint:
    name: black
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Black
        uses: psf/black@stable
        with:
          options: "--check --verbose"